sudo: false
language: php
php:
  - 5.6
  - 7
  - hhvm
before_script:
  - wget https://github.com/puli/cli/releases/download/1.0.0-beta9/puli.phar
  - php puli.phar self-update
  - composer self-update
  - composer install
script:
  - phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
